# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StylizeImage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StylizeImage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12StylizeImage.proto\"<\n\x08\x42\x36\x34Image\x12\x18\n\x10\x62\x36\x34image_content\x18\x01 \x01(\t\x12\x16\n\x0e\x62\x36\x34image_style\x18\x02 \x01(\t\" \n\x0c\x42\x36\x34Image_out\x12\x10\n\x08\x62\x36\x34image\x18\x01 \x01(\t2<\n\x0cStylizeImage\x12,\n\x0eStylized_Image\x12\t.B64Image\x1a\r.B64Image_out\"\x00\x62\x06proto3'
)




_B64IMAGE = _descriptor.Descriptor(
  name='B64Image',
  full_name='B64Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='b64image_content', full_name='B64Image.b64image_content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b64image_style', full_name='B64Image.b64image_style', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=82,
)


_B64IMAGE_OUT = _descriptor.Descriptor(
  name='B64Image_out',
  full_name='B64Image_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='b64image', full_name='B64Image_out.b64image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['B64Image'] = _B64IMAGE
DESCRIPTOR.message_types_by_name['B64Image_out'] = _B64IMAGE_OUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

B64Image = _reflection.GeneratedProtocolMessageType('B64Image', (_message.Message,), {
  'DESCRIPTOR' : _B64IMAGE,
  '__module__' : 'StylizeImage_pb2'
  # @@protoc_insertion_point(class_scope:B64Image)
  })
_sym_db.RegisterMessage(B64Image)

B64Image_out = _reflection.GeneratedProtocolMessageType('B64Image_out', (_message.Message,), {
  'DESCRIPTOR' : _B64IMAGE_OUT,
  '__module__' : 'StylizeImage_pb2'
  # @@protoc_insertion_point(class_scope:B64Image_out)
  })
_sym_db.RegisterMessage(B64Image_out)



_STYLIZEIMAGE = _descriptor.ServiceDescriptor(
  name='StylizeImage',
  full_name='StylizeImage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=118,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='Stylized_Image',
    full_name='StylizeImage.Stylized_Image',
    index=0,
    containing_service=None,
    input_type=_B64IMAGE,
    output_type=_B64IMAGE_OUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STYLIZEIMAGE)

DESCRIPTOR.services_by_name['StylizeImage'] = _STYLIZEIMAGE

# @@protoc_insertion_point(module_scope)
